site_name: Awesome Boat Tech
site_url: https://sy-sea-jade.github.io/awesome-boat-tech/
site_description: Awesome List for Boat Technology including NMEA, Marine Internet, Open Source Projects, Hardware Products, Blogs, Vlogs, Forums and more

repo_name: SY-Sea-Jade/awesome-boat-tech
repo_url: https://github.com/SY-Sea-Jade/awesome-boat-tech

theme:
  name: material
  highlightjs: true
  language: en
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search
    - search.share
plugins:
  - search
  - social:
      cards_layout_options:
        background_color: blue
        background_image: docs/images/social-preview.jpg
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - smarty
  - toc:
      permalink: true
  - sane_lists
  - pymdownx.snippets:
      check_paths: true

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SY-Sea-Jade/awesome-boat-tech
