[project]
site_name = "Awesome Boat Tech"
site_url = "https://awesome-boat-tech.rhizomatics.org.uk"
site_author = "Jey Burrows"
site_description = "A curated list of marine electronics, NMEA, SignalK, OpenCPN and other open source boat tech projects, vendor hardware and software, blogs and forums."

docs_dir = "docs"
site_dir = "site"

repo_url = "https://github.com/SY-Sea-Jade/awesome-boat-tech"
repo_name = "SY-Sea-Jade/awesome-boat-tech"

copyright = "CC0 1.0 Universal (CC0 1.0) Public Domain Dedication. No Rights Reserved."

nav = [
  {"Home" = "index.md"},
  {"Social Media" = "social_media.md"},
  {"Charts" = "charts.md"},
  {"Open Source Projects" = "open-source-projects.md"},
  {"Protocols" = "protocols.md"},
  {"Vendors" = "vendors.md"},
  {"News, Education and Reference" = "education.md"},
  {"Contributing" = "contributing.md"}
]

[project.theme]
language = "en"
logo = "images/logo.jpg"
features = [
  "content.action.edit", # Edit this page
  "content.action.view",  # View source of this page
  "search.highlight",
  "navigation.instant",
  "navigation.tracking",
  "navigation.sections",
  "navigation.expand",
  "navigation.path",
  "navigation.tabs",
  "toc.follow",
  "toc.integrate",
  "navigation.top"
]

[project.markdown_extensions.toc]
permalink = true

[project.markdown_extensions.pymdownx.snippets]

[project.markdown_extensions.admonition]

[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.attr_list]

[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.smartsymbols]
